create table if not exists workout_entries (
  id bigint generated by default as identity primary key,
  day text not null,
  exercise_index integer not null,
  exercise_name text,
  note text,
  sets integer,
  reps integer,
  weight integer,
  updated_at timestamptz default now()
);

create unique index if not exists workout_entries_day_idx
  on workout_entries (day, exercise_index);

alter table workout_entries enable row level security;

create policy "public read" on workout_entries
  for select using (true);

create policy "public insert" on workout_entries
  for insert with check (true);

create policy "public update" on workout_entries
  for update using (true);
