create table if not exists workout_entries (
  id bigint generated by default as identity primary key,
  day text not null,
  exercise_index integer not null,
  exercise_name text,
  note text,
  sets integer,
  reps integer,
  weight integer,
  completed boolean default false,
  updated_at timestamptz default now()
);

create unique index if not exists workout_entries_day_idx
  on workout_entries (day, exercise_index);

alter table workout_entries enable row level security;

create policy "public read" on workout_entries
  for select using (true);

create policy "public insert" on workout_entries
  for insert with check (true);

create policy "public update" on workout_entries
  for update using (true);


alter table workout_entries add column if not exists completed boolean default false;

create table if not exists session_counts (
  year integer primary key,
  count integer not null default 0,
  updated_at timestamptz default now()
);

alter table session_counts enable row level security;

create policy "public read" on session_counts
  for select using (true);

create policy "public insert" on session_counts
  for insert with check (true);

create policy "public update" on session_counts
  for update using (true);
